BitonicSortVSQuickSort: BitonicSortVSQuickSort.c QuickSort.c BitonicSort.c
	mpicc BitonicSortVSQuickSort.c QuickSort.c BitonicSort.c -lm -O3 -I/usr/lpp/ppe.hpct/include -L/usr/lpp/ppe.hpct/lib -lhpc -lpmapi -o ../bin/BitonicSortVSQuickSort
